---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cat-deployment
  labels:
    app: cat
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cat
  template:
    metadata:
      labels:
        app: cat
    spec:
      containers:
        - name: cat
          image: janesee3/cat-application:1
---
apiVersion: v1
kind: Service
metadata:
  name: cat-service
spec:
  selector:
    app: cat
  ports:
    - protocol: TCP
      port: 8080
