# apiVersion: v1
# kind: Pod
# metadata:
#   name: meow
# spec:
#   containers:
#     - name: meow
#       image: janesee3/meow-application:1

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: meow-deployment
  labels:
    app: meow
spec:
  replicas: 3
  selector:
    matchLabels:
      app: meow
  template:
    metadata:
      labels:
        app: meow
    spec:
      containers:
        - name: meow
          image: janesee3/meow-application:1
          env:
            - name: DO_YOU_LIKE_CATS
              value: "it depends"
            - name: CATS_URL
              value: "http://cat-service:8080/cats"
---
apiVersion: v1
kind: Service
metadata:
  name: meow-service
spec:
  selector:
    app: meow
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8080
