# apiVersion: v1
# kind: Pod
# metadata:
#   name: meow
# spec:
#   containers:
#     - name: meow
#       image: janesee3/cat-application:1

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: meow-deployment
  labels:
    app: meow
spec:
  replicas: 3
  selector:
    matchLabels:
      app: meow
  template:
    metadata:
      labels:
        app: meow
    spec:
      containers:
        - name: meow
          image: janesee3/cat-application:1
